# Generated by Django 4.0.4 on 2022-07-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_game_user_alter_comment_id_alter_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Action'), ('AV', 'Adventure'), ('C', 'Casual'), ('I', 'Indie'), ('MMO', 'Massively Multiplayer Online Game'), ('R', 'Racing'), ('S', 'Sports'), ('SM', 'Simulation'), ('RPG', 'Role Playing Game'), ('ST', 'Strategy'), ('F', 'Free To Play'), ('EA', 'Early Access'), ('H', 'Horror'), ('D', 'Dating'), ('P', 'Puzzle'), ('VN', 'Visual Novel'), ('HO', 'Hidden Object'), ('SB', 'Sandbox Games'), ('TPS', 'Third Person Shooter'), ('FPS', 'First Person Shooter'), ('FR', 'Farming'), ('OW', 'Open World'), ('SU', 'Survival'), ('RY', 'Rhythm'), ('BG', 'Boardgame'), ('CG', 'Cardgame'), ('PB', 'Party Based'), ('SF', 'Science Fiction'), ('CO', 'Cooperative')], default='A', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='main_app.genre'),
        ),
    ]
