# Generated by Django 4.0.6 on 2022-07-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
