# Generated by Django 2.2.12 on 2022-07-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20220720_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
    ]
