# Generated by Django 4.0.6 on 2022-07-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_comment_id_alter_game_id_alter_genre_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='profile',
        ),
    ]
